import { PhrasePack } from './types';

export const PHRASE_PACK_V1: PhrasePack = {
  version: 1,
  updatedAtISO: '2026-02-09T12:00:00.000Z',
  phrases: [
    // Discipline
    {
      id: 'discipline_01',
      category: 'Discipline',
      text: 'Discipline is deciding once what you won’t renegotiate daily.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'discipline_02',
      category: 'Discipline',
      text: 'Rules beat moods. Every time.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'discipline_03',
      category: 'Discipline',
      text: 'You don’t need to feel ready. You need to move.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'discipline_04',
      category: 'Discipline',
      text: 'Discipline is quiet. That’s why most people skip it.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'discipline_05',
      category: 'Discipline',
      text: 'Do it now so you don’t carry it all day.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'discipline_06',
      category: 'Discipline',
      text: 'Your future self is built by boring decisions.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'discipline_07',
      category: 'Discipline',
      text: 'Excuses feel good. Discipline works.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'discipline_08',
      category: 'Discipline',
      text: 'Show up even when no one is watching.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'discipline_09',
      category: 'Discipline',
      text: 'You’re not tired of effort. You’re tired of inconsistency.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'discipline_10',
      category: 'Discipline',
      text: 'What you do today sets the tone for tomorrow.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },

    // Training
    {
      id: 'training_01',
      category: 'Training',
      text: 'Train for progress, not validation.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_02',
      category: 'Training',
      text: 'A mediocre session still counts.',
      tone: 'push',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'training_03',
      category: 'Training',
      text: 'Consistency builds what motivation never will.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_04',
      category: 'Training',
      text: 'Train your body to keep promises.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'training_05',
      category: 'Training',
      text: 'Strength comes from showing up again.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_06',
      category: 'Training',
      text: 'You don’t need perfect form. You need honest effort.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_07',
      category: 'Training',
      text: 'The work compounds even when results don’t show yet.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_08',
      category: 'Training',
      text: 'Train even when today feels off.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'training_09',
      category: 'Training',
      text: 'Skill is built under repetition.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'training_10',
      category: 'Training',
      text: 'Every session is a vote for who you’re becoming.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },

    // Mindset
    {
      id: 'mindset_01',
      category: 'Mindset',
      text: 'Your inner dialogue shapes your outer results.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'mindset_02',
      category: 'Mindset',
      text: 'Thoughts repeated become beliefs.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'mindset_03',
      category: 'Mindset',
      text: 'You don’t need certainty to act.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'mindset_04',
      category: 'Mindset',
      text: 'Most limits dissolve once challenged.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'mindset_05',
      category: 'Mindset',
      text: 'Control your focus or it will control you.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'mindset_06',
      category: 'Mindset',
      text: 'Not every thought deserves your attention.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'mindset_07',
      category: 'Mindset',
      text: 'Beliefs are habits you can change.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'mindset_08',
      category: 'Mindset',
      text: 'Clarity comes after action, not before.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'mindset_09',
      category: 'Mindset',
      text: 'Your standards shape your identity.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'mindset_10',
      category: 'Mindset',
      text: 'What you tolerate becomes normal.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },

    // Recovery
    {
      id: 'recovery_01',
      category: 'Recovery',
      text: 'Recovery is not weakness. It’s strategy.',
      tone: 'recovery',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'recovery_02',
      category: 'Recovery',
      text: 'Rest now or be forced to later.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'recovery_03',
      category: 'Recovery',
      text: 'Recovery protects your progress.',
      tone: 'recovery',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'recovery_04',
      category: 'Recovery',
      text: 'Your nervous system needs training too.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'recovery_05',
      category: 'Recovery',
      text: 'Pause on purpose.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'recovery_06',
      category: 'Recovery',
      text: 'You grow between sessions.',
      tone: 'recovery',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'recovery_07',
      category: 'Recovery',
      text: 'Burnout starts when rest feels optional.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'recovery_08',
      category: 'Recovery',
      text: 'Recover to train again, not to escape.',
      tone: 'recovery',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'recovery_09',
      category: 'Recovery',
      text: 'Rest without guilt.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'recovery_10',
      category: 'Recovery',
      text: 'Longevity beats short-term grind.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },

    // Focus
    {
      id: 'focus_01',
      category: 'Focus',
      text: 'Attention is your most valuable resource.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_02',
      category: 'Focus',
      text: 'One task done well beats ten half-done.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_03',
      category: 'Focus',
      text: 'Focus is a decision, not a feeling.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'focus_04',
      category: 'Focus',
      text: 'Distraction is expensive.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_05',
      category: 'Focus',
      text: 'Finish what you start.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_06',
      category: 'Focus',
      text: 'Deep work builds real progress.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'focus_07',
      category: 'Focus',
      text: 'Clarity comes from commitment.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_08',
      category: 'Focus',
      text: 'Do the next right thing.',
      tone: 'push',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'focus_09',
      category: 'Focus',
      text: 'Protect your focus like training time.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'focus_10',
      category: 'Focus',
      text: 'Presence beats speed.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },

    // Consistency
    {
      id: 'consistency_01',
      category: 'Consistency',
      text: 'Small actions done daily win.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_02',
      category: 'Consistency',
      text: 'Momentum beats intensity.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_03',
      category: 'Consistency',
      text: 'Miss once, return immediately.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'consistency_04',
      category: 'Consistency',
      text: 'Consistency is self-respect in action.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'consistency_05',
      category: 'Consistency',
      text: 'Daily effort compounds quietly.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_06',
      category: 'Consistency',
      text: 'Repeatable beats impressive.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_07',
      category: 'Consistency',
      text: 'Progress loves rhythm.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_08',
      category: 'Consistency',
      text: 'Habits build identity.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'consistency_09',
      category: 'Consistency',
      text: 'Show up again.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'consistency_10',
      category: 'Consistency',
      text: 'Consistency turns effort into results.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },

    // Strength
    {
      id: 'strength_01',
      category: 'Strength',
      text: 'Strength grows under resistance.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'strength_02',
      category: 'Strength',
      text: 'Heavy days build capable people.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'strength_03',
      category: 'Strength',
      text: 'You’re stronger than your excuses.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'strength_04',
      category: 'Strength',
      text: 'Pressure reveals preparation.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'strength_05',
      category: 'Strength',
      text: 'Strength is earned, not wished.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'strength_06',
      category: 'Strength',
      text: 'The body adapts to demands.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'strength_07',
      category: 'Strength',
      text: 'Choose effort over comfort.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'strength_08',
      category: 'Strength',
      text: 'Strength shows up when it’s needed.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'strength_09',
      category: 'Strength',
      text: 'Train for resilience.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'strength_10',
      category: 'Strength',
      text: 'Hard things make you durable.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },

    // Nutrition
    {
      id: 'nutrition_01',
      category: 'Nutrition',
      text: 'Fuel the work you expect your body to do.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_02',
      category: 'Nutrition',
      text: 'Consistency beats perfection.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_03',
      category: 'Nutrition',
      text: 'Eat like recovery matters.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_04',
      category: 'Nutrition',
      text: 'Nutrition is part of training.',
      tone: 'reality-check',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_05',
      category: 'Nutrition',
      text: 'Your plate supports your goals.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_06',
      category: 'Nutrition',
      text: 'Discipline applies here too.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_07',
      category: 'Nutrition',
      text: 'Short-term pleasure has long-term cost.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_08',
      category: 'Nutrition',
      text: 'Feed performance, not impulses.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_09',
      category: 'Nutrition',
      text: 'Simple choices repeated win.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'nutrition_10',
      category: 'Nutrition',
      text: 'Nutrition compounds daily.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },

    // Confidence
    {
      id: 'confidence_01',
      category: 'Confidence',
      text: 'Confidence is evidence collected.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'confidence_02',
      category: 'Confidence',
      text: 'Keep promises to yourself.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'confidence_03',
      category: 'Confidence',
      text: 'Confidence follows action.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'confidence_04',
      category: 'Confidence',
      text: 'Self-trust is built, not assumed.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'confidence_05',
      category: 'Confidence',
      text: 'You earn confidence by showing up.',
      tone: 'push',
      intensity: 2,
      isNotifSafe: true,
    },
    {
      id: 'confidence_06',
      category: 'Confidence',
      text: 'Proof beats affirmations.',
      tone: 'reality-check',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'confidence_07',
      category: 'Confidence',
      text: 'Act first. Believe after.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'confidence_08',
      category: 'Confidence',
      text: 'Confidence grows in silence.',
      tone: 'grounding',
      intensity: 1,
      isNotifSafe: true,
    },
    {
      id: 'confidence_09',
      category: 'Confidence',
      text: 'Follow-through builds self-respect.',
      tone: 'push',
      intensity: 3,
      isNotifSafe: true,
    },
    {
      id: 'confidence_10',
      category: 'Confidence',
      text: 'Trust yourself by doing.',
      tone: 'grounding',
      intensity: 2,
      isNotifSafe: true,
    },
  ],
};
